//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anotacion
    {
        public int idAnotacion { get; set; }
        public string nombreUsuario { get; set; }
        public string datosCliente { get; set; }
        public string observacion { get; set; }
        public long imei { get; set; }
        public int idTipoAnotacion { get; set; }
    
        public virtual TipoAnotacion TipoAnotacion { get; set; }
    }
}
