//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int idOrden { get; set; }
        public Nullable<long> imei { get; set; }
        public string serie { get; set; }
        public Nullable<long> imeiSustituido { get; set; }
        public System.DateTime fecha { get; set; }
        public string nombreUsuario { get; set; }
        public string datosCliente { get; set; }
        public string cedulaCliente { get; set; }
        public string pedido { get; set; }
        public int telefono { get; set; }
        public int idModelo { get; set; }
        public int idFormaPago { get; set; }
        public int idTipoTramite { get; set; }
    
        public virtual FormaPago FormaPago { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual TipoTramite TipoTramite { get; set; }
    }
}
